package com.example.myapplication.utils

import com.example.myapplication.data.models.*
import com.example.myapplication.network.AppLanguage

val RussianStrings = UiStrings(
    appName = "Vetro",
    searchPlaceholder = "Поиск в коллекции...",
    newestFirst = "Сначала новые",
    oldestFirst = "Сначала старые",
    titleAZ = "По названию (А-Я)",
    titleZA = "По названию (Я-А)",
    episodesHigh = "Серий больше",
    episodesLow = "Серий меньше",
    ratingHigh = "Высокий рейтинг",
    ratingLow = "Низкий рейтинг",
    favorites = "Избранное",
    settings = "Настройки",
    emptyTitle = "В папке пусто",
    emptySubtitle = "Кажется, здесь еще ничего нет.",
    noResults = "Ничего не найдено",
    noResultsInLibrary = "Нет в вашем списке",
    noFavorites = "Нет избранного",
    filterByGenre = "По жанрам",
    genreAnime = "Аниме / Манга",
    genreMovies = "Фильмы",
    genreSeries = "Сериалы",
    genreFilterAnimeTitle = "Аниме-сериалы",
    genreFilterMoviesTitle = "Фильмы",
    genreFilterSeriesTitle = "Сериалы",
    genreFilterDone = "Готово",
    statsTitle = "Ваша статистика",
    statsSubtitle = "Все, что вы посмотрели",
    episodesWatched = "Всего эпизодов",
    timeSpent = "Затраченное время",
    avgRating = "Средний рейтинг",
    statsTotal = "Всего",
    statsChartsGenresTitle = "Жанры в срезе",
    statsGenreOther = "Прочее",
    statsNoGenreData = "Добавьте жанры к тайтлам, чтобы увидеть графики.",
    statsOk = "ОК",
    statsCardRatingTitle = "Качество жанров",
    statsCardFrequencyTitle = "Частотность жанров",
    statsCardOverviewTitle = "Обзор коллекции",
    statsDeckHint = "Свайп вниз — следующая · тап — подробнее",
    statsAiTitle = "Что это значит",
    statsAiUnavailable = "Подключите ИИ в настройках, чтобы получать объяснения статистики.",
    statsAiInsufficient = "Пока недостаточно данных для выводов.",
    rankTitle = "Ваш ранг:",
    deleteTitle = "Удалить тайтл?",
    deleteSubtitle = "Это действие нельзя будет отменить.",
    deleteConfirm = "Удалить",
    favTitle = "Добавить в избранное?",
    favSubtitle = "Будущий вы скажет вам «спасибо» :)",
    favConfirm = "В избранное",
    menuDeleteSnark = "Уверен? Этот тайтл ничего тебе плохого не сделал… вроде бы. 🤷",
    menuAddFavoriteSnark = "В избранное? Смело. Будто ты правда будешь это пересматривать. 😏",
    cancel = "Отмена",
    addTitle = "Добавить тайтл",
    editTitle = "Изменить",
    animeTitleHint = "Название аниме",
    episodesHint = "Просмотрено серий",
    addPhoto = "Добавить фото",
    enterTitleToast = "Введите название",
    updatedToast = "Обновлено: ",
    languageName = "RU",
    settingsScreenTitle = "Настройки",
    languageCardTitle = "Язык",
    langRu = "Русский",
    langEn = "English",
    themeTitle = "Тема оформления",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    themeSystem = "Системная",
    checkForUpdateTitle = "Обновление приложения",
    checkButtonText = "Проверить",
    updateTileChecking = "Проверка...",
    updateTileAvailable = "Доступно обновление",
    updateTileUpToDate = "Установлена последняя версия",
    updateTileVersionLabel = "Версия",
    updateTileCardTitle = "Обновление",
    updateTileNewVersionSubtitle = "Доступна новая версия",
    updateDialogTitle = "Доступно обновление",
    updateDialogDescription = "Доступна версия %1${'$'}s (%2${'$'}s). Хотите обновить приложение?",
    updateApkSizeUnit = "МБ",
    updateWhatsNewTitle = "Что нового",
    updateWhatsNewFallback = "Улучшения производительности и исправления ошибок",
    updateInstallLater = "Установить позже",
    updateInstallNow = "Обновить",
    updateDownloadProgressFormat = "Загрузка %1${'$'}d%%",
    updateChangelogEmpty = "Список изменений пуст",
    updateChangelogLoadError = "Не удалось загрузить список изменений",
    updateCloseCd = "Закрыть",
    updateOpenInstallPermission = "Разрешить установку из других источников",
    updateSheetNoUpdateDetail = "Установлено: %1${'$'}s. Последний релиз на GitHub совпадает с вашей сборкой (%2${'$'}s). Стороннего обновления нет.",
    updateRetryCheck = "Проверить снова",
    contactTitle = "Связь со мной",
    contactSubtitle = "Нашли баг или есть идея?",
    contactSupportSubtitle = "Нашли баг или есть идея? Напишите мне!",
    donationCardTitle = "Вложись в мои дурные привычки",
    donationCardSubtitle = "Поддержка разработки",
    nottifPanelTitle = "Синхронизация",
    nottifPanelSubtitle = "Уведомления и подключение",
    nottifLastSyncTitle = "Последняя синхронизация",
    nottifLastSyncSub = "Время обновления",
    nottifStatusTitle = "Статус",
    nottifStatusSub = "Активный канал",
    nottifAccountTitle = "Мой Vetro",
    nottifLogoutConfirmTitle = "Выйти из аккаунта?",
    nottifLogoutConfirmBody = "Локальные данные будут удалены. Вы будете перенаправлены на экран приветствия.",
    nottifSyncNow = "Синх.",
    nottifLastSyncSuccess = "Успешно",
    nottifLastSyncSyncing = "Синхронизация…",
    nottifLastSyncError = "Ошибка",
    nottifLastSyncNeedsLogin = "Нужен вход",
    nottifLastSyncConflict = "Конфликт",
    nottifDateToday = "Сегодня",
    nottifBadgeAutomated = "АВТО",
    nottifBadgeManual = "ВРУЧНУЮ",
    nottifStatusConnected = "Подключено",
    nottifStatusDisconnected = "Отключено",
    nottifAccountSignedIn = "Выполнен вход",
    nottifAccountGuest = "Не в аккаунте",
    nottifCloseCd = "Закрыть",
    nottifSectionAccount = "Аккаунт",
    syncModeTitle = "Режим синхронизации",
    syncAuto = "Авто",
    syncManual = "Ручная",
    contentTypeTitle = "Тип контента",
    typeAnime = "Аниме",
    typeMovies = "ТВ",
    cloudSettingsTitle = "Настройки аккаунта",
    cloudSettingsSubtitle = "Синхронизация, вход и пароль",
    cloudTotalSize = "Общий размер",
    cloudFiles = "Файлов",
    syncLabel = "Синх.",
    wifiOnly = "Только Wi-Fi",
    anyNetwork = "Любая сеть",
    lastSync = "Последняя синхр.",
    never = "Никогда",
    externalResults = "ВНЕШНИЕ РЕЗУЛЬТАТЫ",
    apiSearch = "Поиск по API",
    addButton = "Добавить",
    addedButton = "Добавлено",
    viaApi = "через API",
    episodesShort = "эп.",
    cloudRestoreTitle = "Загрузка обложек…",
    cloudRestoreSubtitle = "Скачиваем фото из облака. Пожалуйста, подождите.",
    devSectionTitle = "Для разработчиков",
    devMirrorDbTitle = "Зеркалировать внутреннюю БД",
    devMirrorDbSubtitle = "После каждого изменения копировать базу в app storage/Vetro/anime.db",
    devHideShareTitle = "Скрыть кнопку Share",
    devHideShareSubtitle = "Убирает кнопку экспорта из угла экрана настроек",
    devExportLogsTitle = "Логи",
    devExportLogsSubtitle = "Собрать logcat и открыть системное меню «Поделиться»",
    devImportDbTitle = "Импорт базы",
    devImportDbSubtitle = "Выбрать .db и добавить отсутствующие записи",
    devFpsOverlayTitle = "Диагностика производительности (FPS)",
    devFpsOverlaySubtitle = "Показывать FPS-плашку поверх всех экранов приложения",
    devAdaptiveGlassTitle = "Adaptive glass при скролле",
    devAdaptiveGlassSubtitle = "Снижает blur и lens во время прокрутки списка для экономии GPU. Выключите для сравнения с полным glass.",
    devExportLogsCd = "Экспорт логов",
    devImportDbCd = "Импорт базы",
    devImportDbResultAddedTemplate = "Импорт завершен: добавлено %d записей",
    devImportDbResultNoNew = "Импорт завершен: новых записей не найдено",
    devImportDbResultInvalid = "Не удалось импортировать файл базы данных",
    devExportPdfTitle = "Экспорт в PDF",
    devExportPdfSubtitle = "Таблица коллекции: название, серии, рейтинг",
    devExportPdfCd = "Экспорт PDF",
    devExportPdfDocumentTitle = "Моя коллекция",
    devExportPdfColumnTitle = "Название",
    devExportPdfColumnEpisodes = "Серии",
    devExportPdfColumnRating = "Рейтинг",
    devExportPdfEmpty = "Нет записей",
    inspectTitle = "Поиск по кадру",
    inspectModeAnime = "Аниме",
    inspectModeMoviesTv = "Фильмы / сериалы",
    inspectPickScreenshot = "Нажмите, чтобы выбрать скриншот",
    inspectBack = "Назад",
    inspectClearPhoto = "Сбросить фото",
    inspectLoadingAnalyzing = "Анализ скриншота…",
    inspectReadImageFailed = "Не удалось прочитать изображение",
    inspectNoResults = "Совпадений не найдено",
    inspectErrorGeneric = "Произошла ошибка",
    inspectGeminiRequiredRuAnime = "Подключите AI-провайдера в «AI Connect», чтобы искать аниме на русском по скриншоту.",
    inspectGeminiRequiredMovies = "Подключите AI-провайдера с поддержкой изображений в «AI Connect», чтобы искать фильмы и сериалы по скриншоту.",
    inspectGeminiKeyTitle = "Gemini API-ключ",
    inspectGeminiKeyInputPlaceholder = "Вставьте API-ключ",
    inspectGeminiGetKeyOneClick = "Получить ключ в один клик",
    inspectGeminiTenSecondsHint = "Займёт ~10 секунд",
    inspectGeminiNextStep = "Следующий шаг",
    inspectGeminiInstructionTitle = "Войти в сервис Gemini",
    inspectGeminiInstructionBody = "Для поиска фильмов/ТВ по кадру нужен ваш персональный API-ключ Gemini.",
    inspectGeminiInstructionStepOpen = "Откройте Google AI Studio",
    inspectGeminiInstructionStepCreate = "Нажмите Create API Key",
    inspectGeminiInstructionStepCopy = "Скопируйте ключ и вернитесь в приложение",
    inspectGeminiSaveKey = "Сохранить ключ",
    inspectGeminiCheckAndSave = "Проверить и сохранить",
    inspectGeminiCheckingKey = "Проверка API-ключа…",
    inspectGeminiInvalidFormat = "Некорректный формат API-ключа.",
    inspectGeminiSaved = "API-ключ сохранён.",
    inspectGeminiSaveError = "Не удалось сохранить API-ключ.",
    inspectGeminiCheckErrorTitle = "Ключ недоступен или неверный",
    inspectGeminiBackToInstruction = "Далее",
    inspectGeminiKeyFoundInserted = "Ключ найден и вставлен",
    inspectVisualSearchToolbarTitle = "Visual Search",
    inspectSegmentMoviesTv = "Фильмы / ТВ",
    inspectImageFormatsHint = "JPEG, PNG ДО 10 МБ",
    inspectPoweredByFooter = "POWERED BY VETRO VISION ENGINE",
    sortSheetTitle = "Сортировка",
    sortSheetSubtitle = "Упорядочьте список",
    sortApply = "Применить",
    sortSubtitleRating = "Лучшие по оценке",
    sortSubtitleEpisodes = "Больше серий",
    sortSubtitleTitle = "По алфавиту",
    sortSubtitleGenres = "Тип категории",
    sortTileEpisodesTitle = "Эпизоды",
    sortOrderAscending = "По возрастанию",
    sortOrderDescending = "По убыванию",
    cdSort = "Сортировка",
    cdNotifications = "Уведомления",
    addEditCoverPlaceholderTitle = "Пока без обложки",
    addEditCoverPlaceholderSubtitle = "Выберите изображение из галереи — постер или кадр.",
    addEditCoverPlaceholderButton = "Добавить обложку",
    addEditSectionTitle = "НАЗВАНИЕ",
    addEditSectionEpisodes = "ПРОСМОТРЕНО СЕРИЙ",
    addEditSectionQuickSelect = "БЫСТРЫЙ ВЫБОР",
    addEditSectionFormat = "ФОРМАТ",
    addEditSectionRating = "РЕЙТИНГ",
    addEditSectionComment = "КОММЕНТАРИЙ",
    addEditTitlePlaceholder = "Введите название...",
    addEditEpisodesPlaceholder = "00",
    addEditFormatAnimeTitle = "Аниме-сериалы",
    addEditFormatAnimeSubtitle = "Сезонные и регулярные выпуски",
    addEditFormatMoviesTitle = "Фильмы",
    addEditFormatMoviesSubtitle = "Полнометражные картины",
    addEditFormatSeriesTitle = "Сериалы",
    addEditFormatSeriesSubtitle = "Традиционные форматы вещания",
    nottifTileSyncTitle = "Синхронизация",
    nottifServiceShikimori = "Shikimori",
    nottifServiceMal = "MAL",
    nottifServiceAnilist = "AniList",
    malSyncPlaceholderBody = "MyAnimeList работает… теоретически\nПрактика показывает немного другое.\nМы держим руку на пульсе — пока нитевидный",
    nottifServiceActionDialogMessage = "Выберите действие",
    nottifServiceActionPull = "Импорт БД (Pull)",
    nottifServiceActionPush = "Экспорт БД (Push)",
    nottifServiceActionSync = "Синхронизация (Sync)",
    listSyncLoadingDefaultMessage = "Синхронизация…",
    listSyncLoadingSubtitle = "СИСТЕМНАЯ СИНХРОНИЗАЦИЯ",
    listSyncLoadingFooter = "Пожалуйста, не закрывайте приложение до завершения процесса",
    splashStorageMigrationTitle = "Оптимизация хранилища…",
    splashStorageMigrationSubtitle = "Переносим данные в защищённое хранилище. Это может занять немного времени.",
    splashJsonMigrationTitle = "Оптимизация…",
    splashJsonMigrationSubtitle = "Адаптируем данные под новую версию. Это займет пару секунд.",
    splashLegacyFolderTitle = "Перенос обложек",
    splashLegacyFolderSubtitle = "Выберите папку Documents/Vetro (или Vetro/collection), чтобы импортировать старые обложки.",
    splashLegacyFolderAction = "Выбрать папку",
    splashLegacyFolderSkip = "Пропустить",
)

val EnglishStrings = UiStrings(
    appName = "Vetro",
    searchPlaceholder = "Search collection...",
    newestFirst = "Newest First",
    oldestFirst = "Oldest First",
    titleAZ = "Name (A-Z)",
    titleZA = "Name (Z-A)",
    episodesHigh = "Episodes (high)",
    episodesLow = "Episodes (low)",
    ratingHigh = "Highest Rated",
    ratingLow = "Lowest Rated",
    favorites = "Favorites",
    settings = "Settings",
    emptyTitle = "Nothing in folder",
    emptySubtitle = "Looks empty over here.",
    noResults = "No results found",
    noResultsInLibrary = "Not in your list",
    noFavorites = "No favorites yet",
    filterByGenre = "By genres",
    genreAnime = "Anime / Manga",
    genreMovies = "Movies",
    genreSeries = "TV Series",
    genreFilterAnimeTitle = "Anime Series",
    genreFilterMoviesTitle = "Movies",
    genreFilterSeriesTitle = "Series",
    genreFilterDone = "Done",
    statsTitle = "Your Watch Stats",
    statsSubtitle = "Everything you've watched so far",
    episodesWatched = "Episodes watched",
    timeSpent = "Time spent watching",
    avgRating = "Average rating",
    statsTotal = "Total",
    statsChartsGenresTitle = "Genres at a glance",
    statsGenreOther = "Other",
    statsNoGenreData = "Add genre tags to titles to see the charts.",
    statsOk = "OK",
    statsCardRatingTitle = "Genre quality",
    statsCardFrequencyTitle = "Genre frequency",
    statsCardOverviewTitle = "Collection overview",
    statsDeckHint = "Swipe down for next · tap for details",
    statsAiTitle = "What it means",
    statsAiUnavailable = "Connect AI in settings to get explanations of your stats.",
    statsAiInsufficient = "Not enough data for insights yet.",
    rankTitle = "Your rank:",
    deleteTitle = "Delete title?",
    deleteSubtitle = "There is no undo.",
    deleteConfirm = "Delete",
    favTitle = "Add to favorites?",
    favSubtitle = "Future you will thank you.",
    favConfirm = "Set Favorite",
    menuDeleteSnark = "You sure? This title hasn't done anything wrong… yet. 😬",
    menuAddFavoriteSnark = "Add to favorites? Bold of you to assume you'll ever rewatch it. 😏",
    cancel = "Cancel",
    addTitle = "Add title",
    editTitle = "Edit title",
    animeTitleHint = "Anime Title",
    episodesHint = "Episodes Watched",
    addPhoto = "Add Photo",
    enterTitleToast = "Enter title",
    updatedToast = "Updated: ",
    languageName = "EN",
    settingsScreenTitle = "Settings",
    languageCardTitle = "Language",
    langRu = "Russian",
    langEn = "English",
    themeTitle = "Themes",
    themeLight = "Light",
    themeDark = "Dark",
    themeSystem = "System",
    checkForUpdateTitle = "App Update",
    checkButtonText = "Check now",
    updateTileChecking = "Checking...",
    updateTileAvailable = "Update available",
    updateTileUpToDate = "Up to date",
    updateTileVersionLabel = "Version",
    updateTileCardTitle = "Update",
    updateTileNewVersionSubtitle = "New version available",
    updateDialogTitle = "Update available",
    updateDialogDescription = "Version %1${'$'}s (%2${'$'}s) is available. Update the app now?",
    updateApkSizeUnit = "MB",
    updateWhatsNewTitle = "What’s new",
    updateWhatsNewFallback = "Performance improvements and bug fixes",
    updateInstallLater = "Install later",
    updateInstallNow = "Update",
    updateDownloadProgressFormat = "Downloading %1${'$'}d%%",
    updateChangelogEmpty = "No changelog for this release",
    updateChangelogLoadError = "Could not load the changelog",
    updateCloseCd = "Close",
    updateOpenInstallPermission = "Allow installing from this source",
    updateSheetNoUpdateDetail = "Installed: %1${'$'}s. The latest GitHub release matches what you already have (%2${'$'}s). There is nothing new to pull.",
    updateRetryCheck = "Check again",
    contactTitle = "Contact me",
    contactSubtitle = "Found a bug or have an idea?",
    contactSupportSubtitle = "Found a bug or have an idea? Let me know!",
    donationCardTitle = "Invest in my bad habits",
    donationCardSubtitle = "Support for development",
    nottifPanelTitle = "Sync Control",
    nottifPanelSubtitle = "Notifications & connectivity",
    nottifLastSyncTitle = "Last Sync",
    nottifLastSyncSub = "Last updated time",
    nottifStatusTitle = "Status",
    nottifStatusSub = "Active signal",
    nottifAccountTitle = "My Vetro",
    nottifLogoutConfirmTitle = "Log out?",
    nottifLogoutConfirmBody = "Local data will be cleared. You will be redirected to the welcome screen.",
    nottifSyncNow = "Sync Now",
    nottifLastSyncSuccess = "Success",
    nottifLastSyncSyncing = "Syncing…",
    nottifLastSyncError = "Error",
    nottifLastSyncNeedsLogin = "Sign in required",
    nottifLastSyncConflict = "Conflict",
    nottifDateToday = "Today",
    nottifBadgeAutomated = "AUTO",
    nottifBadgeManual = "MANUAL",
    nottifStatusConnected = "Connected",
    nottifStatusDisconnected = "Disabled",
    nottifAccountSignedIn = "Signed in",
    nottifAccountGuest = "Not signed in",
    nottifCloseCd = "Close",
    nottifSectionAccount = "Account",
    syncModeTitle = "Sync Mode",
    syncAuto = "Auto",
    syncManual = "Manual",
    contentTypeTitle = "Content Type",
    typeAnime = "Anime",
    typeMovies = "TV",
    cloudSettingsTitle = "Account settings",
    cloudSettingsSubtitle = "Sync, sign-in, and password",
    cloudTotalSize = "Total Size",
    cloudFiles = "Files",
    syncLabel = "Sync Now",
    wifiOnly = "Wi-Fi Only",
    anyNetwork = "Any Network",
    lastSync = "Last Sync",
    never = "Never",
    externalResults = "EXTERNAL RESULTS",
    apiSearch = "API Search",
    addButton = "Add",
    addedButton = "Added",
    viaApi = "via API",
    episodesShort = "ep.",
    cloudRestoreTitle = "Downloading covers…",
    cloudRestoreSubtitle = "Fetching photos from the cloud. Please wait.",
    devSectionTitle = "For developers",
    devMirrorDbTitle = "Mirror internal database",
    devMirrorDbSubtitle = "Copy DB changes to app storage/Vetro/anime.db after each write",
    devHideShareTitle = "Hide Share button",
    devHideShareSubtitle = "Removes the share action from the settings corner button",
    devExportLogsTitle = "Logs",
    devExportLogsSubtitle = "Collect logcat and open Android share sheet",
    devImportDbTitle = "Import database",
    devImportDbSubtitle = "Pick a .db file and add missing entries",
    devFpsOverlayTitle = "Performance diagnostics (FPS)",
    devFpsOverlaySubtitle = "Show an FPS overlay above all app screens",
    devAdaptiveGlassTitle = "Adaptive glass on scroll",
    devAdaptiveGlassSubtitle = "Reduces blur and lens while the list scrolls to save GPU. Turn off to compare with full glass.",
    devExportLogsCd = "Export logs",
    devImportDbCd = "Import database",
    devImportDbResultAddedTemplate = "Import finished: added %d entries",
    devImportDbResultNoNew = "Import finished: no new entries found",
    devImportDbResultInvalid = "Failed to import database file",
    devExportPdfTitle = "Export to PDF",
    devExportPdfSubtitle = "Collection table: title, episodes, rating",
    devExportPdfCd = "Export PDF",
    devExportPdfDocumentTitle = "My collection",
    devExportPdfColumnTitle = "Title",
    devExportPdfColumnEpisodes = "Episodes",
    devExportPdfColumnRating = "Rating",
    devExportPdfEmpty = "No entries",
    inspectTitle = "Search by frame",
    inspectModeAnime = "Anime",
    inspectModeMoviesTv = "Movies / TV",
    inspectPickScreenshot = "Tap to select a screenshot",
    inspectBack = "Back",
    inspectClearPhoto = "Clear image",
    inspectLoadingAnalyzing = "Analyzing screenshot…",
    inspectReadImageFailed = "Could not read image",
    inspectNoResults = "No matches found",
    inspectErrorGeneric = "Something went wrong",
    inspectGeminiRequiredRuAnime = "Connect an AI provider in AI Connect to search anime in Russian from screenshots.",
    inspectGeminiRequiredMovies = "Connect a vision-capable AI provider in AI Connect to search movies and TV from screenshots.",
    inspectGeminiKeyTitle = "Gemini API key",
    inspectGeminiKeyInputPlaceholder = "Paste your API key",
    inspectGeminiGetKeyOneClick = "Get key in one click",
    inspectGeminiTenSecondsHint = "Takes ~10 seconds",
    inspectGeminiNextStep = "Next step",
    inspectGeminiInstructionTitle = "Sign in to Gemini",
    inspectGeminiInstructionBody = "Movies/TV frame search requires your personal Gemini API key.",
    inspectGeminiInstructionStepOpen = "Open Google AI Studio",
    inspectGeminiInstructionStepCreate = "Press Create API Key",
    inspectGeminiInstructionStepCopy = "Copy the key and return to the app",
    inspectGeminiSaveKey = "Save key",
    inspectGeminiCheckAndSave = "Check and save",
    inspectGeminiCheckingKey = "Verifying API key…",
    inspectGeminiInvalidFormat = "Invalid API key format.",
    inspectGeminiSaved = "API key saved.",
    inspectGeminiSaveError = "Could not save API key.",
    inspectGeminiCheckErrorTitle = "Key is invalid or unavailable",
    inspectGeminiBackToInstruction = "Next",
    inspectGeminiKeyFoundInserted = "Key found and inserted",
    inspectVisualSearchToolbarTitle = "Visual Search",
    inspectSegmentMoviesTv = "Movies/TV",
    inspectImageFormatsHint = "JPEG, PNG UP TO 10MB",
    inspectPoweredByFooter = "POWERED BY VETRO VISION ENGINE",
    sortSheetTitle = "Sort by",
    sortSheetSubtitle = "Organize your collection",
    sortApply = "Apply sorting",
    sortSubtitleRating = "Top performance",
    sortSubtitleEpisodes = "Longer series",
    sortSubtitleTitle = "Alphabetical",
    sortSubtitleGenres = "Category type",
    sortTileEpisodesTitle = "Episodes",
    sortOrderAscending = "Ascending",
    sortOrderDescending = "Descending",
    cdSort = "Sort",
    cdNotifications = "Notifications",
    addEditCoverPlaceholderTitle = "No cover yet",
    addEditCoverPlaceholderSubtitle = "Pick an image from your gallery — a poster or a frame.",
    addEditCoverPlaceholderButton = "Add cover",
    addEditSectionTitle = "ANIME TITLE",
    addEditSectionEpisodes = "EPISODES WATCHED",
    addEditSectionQuickSelect = "QUICK SELECT",
    addEditSectionFormat = "FORMAT CATEGORY",
    addEditSectionRating = "RATING",
    addEditSectionComment = "COMMENT",
    addEditTitlePlaceholder = "Enter title name...",
    addEditEpisodesPlaceholder = "00",
    addEditFormatAnimeTitle = "Anime Series",
    addEditFormatAnimeSubtitle = "Ongoing or seasonal releases",
    addEditFormatMoviesTitle = "Movies",
    addEditFormatMoviesSubtitle = "Feature-length cinematic entries",
    addEditFormatSeriesTitle = "Series",
    addEditFormatSeriesSubtitle = "Traditional broadcasting formats",
    nottifTileSyncTitle = "Sync",
    nottifServiceShikimori = "Shikimori",
    nottifServiceMal = "MAL",
    nottifServiceAnilist = "AniList",
    malSyncPlaceholderBody = "MyAnimeList works… theoretically\nIn practice, results may vary.\nWe've got a finger on the pulse — it's flatlining",
    nottifServiceActionDialogMessage = "Choose an action",
    nottifServiceActionPull = "Import (Pull)",
    nottifServiceActionPush = "Export (Push)",
    nottifServiceActionSync = "Sync",
    listSyncLoadingDefaultMessage = "Synchronizing…",
    listSyncLoadingSubtitle = "SYSTEM SYNCING",
    listSyncLoadingFooter = "Please don't close the app until the process finishes",
    splashStorageMigrationTitle = "Optimizing storage…",
    splashStorageMigrationSubtitle = "Moving data to secure storage. This may take a moment.",
    splashJsonMigrationTitle = "Optimizing…",
    splashJsonMigrationSubtitle = "Adapting data for the new version. This will take a few seconds.",
    splashLegacyFolderTitle = "Importing covers",
    splashLegacyFolderSubtitle = "Select the Documents/Vetro folder (or Vetro/collection) to import your old cover images.",
    splashLegacyFolderAction = "Choose folder",
    splashLegacyFolderSkip = "Skip",
)

fun appLocale(language: AppLanguage): java.util.Locale = when (language) {
    AppLanguage.RU -> java.util.Locale.forLanguageTag("ru")
    AppLanguage.EN -> java.util.Locale.US
}

fun formatApkMegabytesNumber(bytes: Long, language: AppLanguage): String {
    val mb = bytes.toFloat() / (1024f * 1024f)
    return String.format(appLocale(language), "%.1f", mb)
}

fun formatApkSizeLabel(bytes: Long?, language: AppLanguage, sizeUnit: String): String? {
    if (bytes == null || bytes <= 0L) return null
    return "${formatApkMegabytesNumber(bytes, language)} $sizeUnit"
}

fun getStrings(lang: AppLanguage): UiStrings = when(lang) {
    AppLanguage.RU -> RussianStrings
    AppLanguage.EN -> EnglishStrings
}

private val RussianNotificationStrings = NotificationStrings(
    updatesTitle = "Обновления",
    updatesChecking = "Проверка API (AniList, Shikimori, TMDB)...\nЭто может занять некоторое время.",
    updatesUpToDate = "У вас все актуально!",
    nottifCheckUpdatesCd = "Проверить новые серии",
    nottifNewEpisodesFormat = "+%d новых серий",
    notifChannelName = "Новые серии",
    notifChannelDesc = "Уведомления о выходе новых серий",
    notifUpdateTitleFormat = "Новая серия: %s",
    notifUpdateBodyFormat = "Отмечено в коллекции: %1\$d → %2\$d эп.",
    notifGroupSummaryFormat = "Новые серии: %d",
    notifMangaChannelName = "Новые главы",
    notifMangaChannelDesc = "Уведомления о выходе новых глав манги",
    notifMangaTitleFormat = "Новая глава: %s",
    notifMangaBodyFormat = "+%1\$d гл. · последняя — %2\$s",
    notifMangaBodyCountFormat = "Новых глав: %d",
    notifMangaGroupSummaryFormat = "Новые главы: %d",
    nottifSyncChipSynced = "ОК",
    nottifSyncChipErrors = "Ошибки",
    nottifSyncChipTotal = "Всего",
)

private val EnglishNotificationStrings = NotificationStrings(
    updatesTitle = "Updates",
    updatesChecking = "Checking APIs (AniList, Shikimori, TMDB)...\nThis will take a moment.",
    updatesUpToDate = "You are up to date!",
    nottifCheckUpdatesCd = "Check for episode updates",
    nottifNewEpisodesFormat = "+%d new episodes",
    notifChannelName = "New episodes",
    notifChannelDesc = "Notifications about newly aired episodes",
    notifUpdateTitleFormat = "New episode: %s",
    notifUpdateBodyFormat = "Marked in your collection: %1\$d → %2\$d ep.",
    notifGroupSummaryFormat = "New episodes: %d",
    notifMangaChannelName = "New chapters",
    notifMangaChannelDesc = "Notifications about newly released manga chapters",
    notifMangaTitleFormat = "New chapter: %s",
    notifMangaBodyFormat = "+%1\$d ch. · latest is %2\$s",
    notifMangaBodyCountFormat = "New chapters: %d",
    notifMangaGroupSummaryFormat = "New chapters: %d",
    nottifSyncChipSynced = "Synced",
    nottifSyncChipErrors = "Errors",
    nottifSyncChipTotal = "Total",
)

fun getNotificationStrings(lang: AppLanguage): NotificationStrings = when (lang) {
    AppLanguage.RU -> RussianNotificationStrings
    AppLanguage.EN -> EnglishNotificationStrings
}

/** Язык интерфейса по системной локали: ru → RU, иначе EN. */
fun systemAppLanguage(): AppLanguage =
    if (java.util.Locale.getDefault().language.equals("ru", ignoreCase = true)) {
        AppLanguage.RU
    } else {
        AppLanguage.EN
    }

/** Отдельно от [UiStrings]: у data class уже ~251 поле, лимит JVM — 255 параметров конструктора. */
data class DevRepairDbStrings(
    val title: String,
    val subtitle: String,
    val contentDescription: String,
    val resultTemplate: String,
    val resultNothing: String,
    val resultFailed: String,
    val logDialogTitle: String,
    val logDialogMessage: String,
    val logDialogCreate: String,
    val logDialogCancel: String,
    val logShareTitle: String,
)

private val RussianDevRepairDbStrings = DevRepairDbStrings(
    title = "Исправить БД",
    subtitle = "Проверить коллекцию и подтянуть недостающие данные из API",
    contentDescription = "Исправить базу данных",
    resultTemplate = "Готово: исправлено %1${'$'}d из %2${'$'}d, пропущено %3${'$'}d, ошибок %4${'$'}d",
    resultNothing = "Проверка завершена: все записи в порядке",
    resultFailed = "Не удалось выполнить проверку базы данных",
    logDialogTitle = "Исправление завершено",
    logDialogMessage = "Создать текстовый лог этой проверки? Его можно отправить в Telegram, почту или другое приложение.",
    logDialogCreate = "Создать",
    logDialogCancel = "Отмена",
    logShareTitle = "Отправить лог исправления БД",
)

private val EnglishDevRepairDbStrings = DevRepairDbStrings(
    title = "Repair database",
    subtitle = "Scan the collection and fetch missing data from the API",
    contentDescription = "Repair database",
    resultTemplate = "Done: fixed %1${'$'}d of %2${'$'}d, skipped %3${'$'}d, failed %4${'$'}d",
    resultNothing = "Check finished: all entries look complete",
    resultFailed = "Failed to run database repair",
    logDialogTitle = "Repair finished",
    logDialogMessage = "Create a text log of this run? You can share it via Telegram, email, or another app.",
    logDialogCreate = "Create",
    logDialogCancel = "Cancel",
    logShareTitle = "Share database repair log",
)

fun getDevRepairDbStrings(lang: AppLanguage): DevRepairDbStrings = when (lang) {
    AppLanguage.RU -> RussianDevRepairDbStrings
    AppLanguage.EN -> EnglishDevRepairDbStrings
}

/** Отдельно от [UiStrings]: лимит JVM — 255 параметров конструктора. Строки «Дубляж названий». */
data class TitleDubbingStrings(
    val title: String,
    val subtitle: String,
    val contentDescription: String,
    val runningTemplate: String,
    val resultTemplate: String,
    val resultNothing: String,
    /** Очередь была, но ни одно название не удалось заполнить. */
    val resultNoneFilled: String,
    val resultFailed: String,
    val noAiTitle: String,
    val noAiMessage: String,
    val noAiConnect: String,
    val noAiCancel: String,
)

private val RussianTitleDubbingStrings = TitleDubbingStrings(
    title = "Дубляж названий",
    subtitle = "Подтянуть английские названия из API, а недостающие перевести через AI",
    contentDescription = "Дубляж названий",
    runningTemplate = "Дубляж: %1${'$'}d из %2${'$'}d",
    resultTemplate = "Готово: заполнено %1${'$'}d из %2${'$'}d названий",
    resultNothing = "Все названия уже заполнены",
    resultNoneFilled = "Не удалось заполнить названия (API/AI не дали english). Запустите дубляж ещё раз",
    resultFailed = "Не удалось выполнить дубляж названий",
    noAiTitle = "AI не подключён",
    noAiMessage = "Часть названий не удалось найти в базах — для их перевода нужен подключённый AI. Подключить сейчас?",
    noAiConnect = "Подключить AI",
    noAiCancel = "Позже",
)

private val EnglishTitleDubbingStrings = TitleDubbingStrings(
    title = "Title dubbing",
    subtitle = "Fetch English titles from APIs and translate the rest with AI",
    contentDescription = "Title dubbing",
    runningTemplate = "Dubbing: %1${'$'}d of %2${'$'}d",
    resultTemplate = "Done: filled %1${'$'}d of %2${'$'}d titles",
    resultNothing = "All titles are already filled",
    resultNoneFilled = "Could not fill any titles (API/AI returned no english). Run dubbing again",
    resultFailed = "Failed to run title dubbing",
    noAiTitle = "AI not connected",
    noAiMessage = "Some titles weren't found in the databases — translating them needs a connected AI provider. Connect now?",
    noAiConnect = "Connect AI",
    noAiCancel = "Later",
)

fun getTitleDubbingStrings(lang: AppLanguage): TitleDubbingStrings = when (lang) {
    AppLanguage.RU -> RussianTitleDubbingStrings
    AppLanguage.EN -> EnglishTitleDubbingStrings
}

/** Отдельно от [UiStrings]: лимит JVM — 255 параметров конструктора. Строки «Обогащение коллекции». */
data class CollectionEnrichmentStrings(
    val cardTitle: String,
    val cardSubtitle: String,
    val sheetTitle: String,
    val fullTitle: String,
    val fullSubtitle: String,
    val fullRunningFields: String,
    val fullRunningTitlesTemplate: String,
    val liveTitle: String,
    val liveSubtitle: String,
    val overflowTitle: String,
    val overflowMessageTemplate: String,
    val overflowCancel: String,
    val overflowStart: String,
)

private val RussianCollectionEnrichmentStrings = CollectionEnrichmentStrings(
    cardTitle = "Обогащение коллекции",
    cardSubtitle = "Подтянуть недостающие данные и названия",
    sheetTitle = "Обогащение коллекции",
    fullTitle = "Полное обогащение",
    fullSubtitle = "Один заход: проверить всю коллекцию и заполнить пробелы через API и AI",
    fullRunningFields = "Обогащение: поля…",
    fullRunningTitlesTemplate = "Названия: %1${'$'}d из %2${'$'}d",
    liveTitle = "Фоновое обновление",
    liveSubtitle = "Потихоньку подтягивать недостающее в фоне, даже когда приложение закрыто",
    overflowTitle = "Слишком много пропусков",
    overflowMessageTemplate = "Найдено записей с неполными данными: %1${'$'}d. Рекомендуем сначала провести полное обогащение.",
    overflowCancel = "Отмена",
    overflowStart = "Начать",
)

private val EnglishCollectionEnrichmentStrings = CollectionEnrichmentStrings(
    cardTitle = "Collection Enrichment",
    cardSubtitle = "Fetch missing data and titles",
    sheetTitle = "Collection Enrichment",
    fullTitle = "Full Enrichment",
    fullSubtitle = "One pass: scan the whole collection and fill gaps via APIs and AI",
    fullRunningFields = "Enriching: fields…",
    fullRunningTitlesTemplate = "Titles: %1${'$'}d of %2${'$'}d",
    liveTitle = "Live Maintenance",
    liveSubtitle = "Gradually fill in what's missing in the background, even when the app is closed",
    overflowTitle = "Too many gaps",
    overflowMessageTemplate = "Entries with incomplete data: %1${'$'}d. We recommend running a full enrichment first.",
    overflowCancel = "Cancel",
    overflowStart = "Start",
)

fun getCollectionEnrichmentStrings(lang: AppLanguage): CollectionEnrichmentStrings = when (lang) {
    AppLanguage.RU -> RussianCollectionEnrichmentStrings
    AppLanguage.EN -> EnglishCollectionEnrichmentStrings
}

/**
 * Строки настроек плеера.
 *
 * Отдельным объектом, а не полями [UiStrings]: у того больше 254 полей роняют release-сборку
 * (`VerifyError` в `clinit`), и в debug это не воспроизводится.
 */
data class PlayerSettingsStrings(
    val autoSkipTitle: String,
    val autoSkipSubtitle: String,
    val autoNextTitle: String,
    val autoNextSubtitle: String,
)

private val RussianPlayerSettingsStrings = PlayerSettingsStrings(
    autoSkipTitle = "Автопропуск",
    autoSkipSubtitle = "Молча перематывать опенинг, эндинг и рекап. Выключено — плеер показывает кнопку «Пропустить»",
    autoNextTitle = "Следующая серия",
    autoNextSubtitle = "Включать следующую серию, когда текущая доиграла. Выключено — плеер останавливается на последнем кадре",
)

private val EnglishPlayerSettingsStrings = PlayerSettingsStrings(
    autoSkipTitle = "Auto-skip",
    autoSkipSubtitle = "Skip openings, endings and recaps silently. When off, the player offers a Skip button instead",
    autoNextTitle = "Next episode",
    autoNextSubtitle = "Start the next episode when the current one ends. When off, the player stops on the last frame",
)

fun getPlayerSettingsStrings(lang: AppLanguage): PlayerSettingsStrings = when (lang) {
    AppLanguage.RU -> RussianPlayerSettingsStrings
    AppLanguage.EN -> EnglishPlayerSettingsStrings
}

/** Строки блока «Где смотреть» (иконки-ссылки на одобренные сайты). */
data class WebLinksStrings(
    val sheetTitle: String,
    val empty: String,
)

fun getWebLinksStrings(lang: AppLanguage): WebLinksStrings = when (lang) {
    AppLanguage.RU -> WebLinksStrings(sheetTitle = "Где смотреть", empty = "Ничего не найдено")
    AppLanguage.EN -> WebLinksStrings(sheetTitle = "Where to watch", empty = "Nothing found")
}

/** Отдельно от [UiStrings]: лимит JVM — 255 параметров конструктора. Строки экрана AI Connect (BYOK). */
data class AiConnectStrings(
    val tileTitle: String,
    val tileSubtitle: String,
    val sheetTitle: String,
    val sheetSubtitle: String,
    val inputPlaceholder: String,
    val connectButton: String,
    val getApiKey: String,
    val storageHint: String,
    val statusDetecting: String,
    val statusValidating: String,
    val statusError: String,
    val connectedLabel: String,
    val emptyHint: String,
    val removeCd: String,
    val showKeyCd: String,
    val hideKeyCd: String,
    val doneButton: String,
)

private val RussianAiConnectStrings = AiConnectStrings(
    tileTitle = "AI Connect",
    tileSubtitle = "Подключите свой AI-ключ (BYOK)",
    sheetTitle = "AI Connect",
    sheetSubtitle = "Вставьте API-ключ — провайдер определится автоматически",
    inputPlaceholder = "API-ключ",
    connectButton = "Подключить",
    getApiKey = "Получить ключ",
    storageHint = "Ключ шифруется и хранится на этом устройстве, а также синхронизируется с вашим аккаунтом.",
    statusDetecting = "Определяем провайдера…",
    statusValidating = "Проверяем ключ…",
    statusError = "Не удалось определить провайдера или ключ недействителен",
    connectedLabel = "Подключено",
    emptyHint = "Пока нет подключённых провайдеров",
    removeCd = "Удалить",
    showKeyCd = "Показать ключ",
    hideKeyCd = "Скрыть ключ",
    doneButton = "Готово",
)

private val EnglishAiConnectStrings = AiConnectStrings(
    tileTitle = "AI Connect",
    tileSubtitle = "Bring your own AI key (BYOK)",
    sheetTitle = "AI Connect",
    sheetSubtitle = "Paste an API key — the provider is detected automatically",
    inputPlaceholder = "API key",
    connectButton = "Connect",
    getApiKey = "Get API Key",
    storageHint = "The key is encrypted and stored on this device, and synced to your account.",
    statusDetecting = "Detecting provider…",
    statusValidating = "Validating key…",
    statusError = "Could not detect the provider or the key is invalid",
    connectedLabel = "Connected",
    emptyHint = "No providers connected yet",
    removeCd = "Remove",
    showKeyCd = "Show key",
    hideKeyCd = "Hide key",
    doneButton = "Done",
)

fun getAiConnectStrings(lang: AppLanguage): AiConnectStrings = when (lang) {
    AppLanguage.RU -> RussianAiConnectStrings
    AppLanguage.EN -> EnglishAiConnectStrings
}

/** Отдельно от [UiStrings]: лимит JVM — 255 параметров конструктора. */
data class WelcomeStrings(
    val appSubtitle: String,
    val supabaseBadge: String,
    val supabaseHint: String,
    val signInGoogle: String,
    val signInGithub: String,
    val orContinueWith: String,
    val emailLabel: String,
    val passwordLabel: String,
    val forgotPassword: String,
    val signInButton: String,
    val continueGuest: String,
    val privacyNote: String,
    val oauthPasswordHint: String,
    val enterEmailFirst: String,
    val loginFailedFormat: String,
    val resetPasswordSuccessFormat: String,
    val resetPasswordErrorFormat: String,
)

private val RussianWelcomeStrings = WelcomeStrings(
    appSubtitle = "Менеджер коллекции аниме и манги",
    supabaseBadge = "Аккаунт Supabase",
    supabaseHint = "Войдите через Supabase, чтобы синхронизировать коллекцию между устройствами",
    signInGoogle = "Войти через Google",
    signInGithub = "Войти через GitHub",
    orContinueWith = "или по email",
    emailLabel = "Email",
    passwordLabel = "Пароль",
    forgotPassword = "Забыли пароль?",
    signInButton = "Войти",
    continueGuest = "Продолжить как гость",
    privacyNote = "Мы не передаём ваши данные третьим лицам и используем шифрование",
    oauthPasswordHint = "Входили через Google или GitHub? Сначала войдите так же и задайте пароль в настройках аккаунта.",
    enterEmailFirst = "Сначала введите email",
    loginFailedFormat = "Ошибка входа: %1\$s",
    resetPasswordSuccessFormat = "Если аккаунт существует, на %1\$s отправлено письмо для сброса пароля",
    resetPasswordErrorFormat = "Ошибка: %1\$s",
)

private val EnglishWelcomeStrings = WelcomeStrings(
    appSubtitle = "Your ultimate anime and manga collection manager",
    supabaseBadge = "Supabase account",
    supabaseHint = "Sign in with Supabase to sync your collection across devices",
    signInGoogle = "Sign in with Google",
    signInGithub = "Sign in with GitHub",
    orContinueWith = "or continue with",
    emailLabel = "Email",
    passwordLabel = "Password",
    forgotPassword = "Forgot password?",
    signInButton = "Sign in",
    continueGuest = "Continue as Guest",
    privacyNote = "We don't share your data with third parties and use encryption",
    oauthPasswordHint = "Signed in with Google or GitHub before? Sign in the same way first, then set a password in account settings.",
    enterEmailFirst = "Enter your email first",
    loginFailedFormat = "Login failed: %1\$s",
    resetPasswordSuccessFormat = "If the account exists, a password reset email was sent to %1\$s",
    resetPasswordErrorFormat = "Error: %1\$s",
)

fun getWelcomeStrings(lang: AppLanguage): WelcomeStrings = when (lang) {
    AppLanguage.RU -> RussianWelcomeStrings
    AppLanguage.EN -> EnglishWelcomeStrings
}

data class AddEditCommentStrings(
    val addButton: String,
    val placeholder: String,
)

private val RussianAddEditCommentStrings = AddEditCommentStrings(
    addButton = "Добавить комментарий",
    placeholder = "Ваш комментарий...",
)

private val EnglishAddEditCommentStrings = AddEditCommentStrings(
    addButton = "Add comment",
    placeholder = "Your comment...",
)

fun getAddEditCommentStrings(lang: AppLanguage): AddEditCommentStrings = when (lang) {
    AppLanguage.RU -> RussianAddEditCommentStrings
    AppLanguage.EN -> EnglishAddEditCommentStrings
}

data class CloudSyncPillStrings(
    val label: String,
)

private val RussianCloudSyncPillStrings = CloudSyncPillStrings(label = "Синх.")
private val EnglishCloudSyncPillStrings = CloudSyncPillStrings(label = "Sync")

fun getCloudSyncPillStrings(lang: AppLanguage): CloudSyncPillStrings = when (lang) {
    AppLanguage.RU -> RussianCloudSyncPillStrings
    AppLanguage.EN -> EnglishCloudSyncPillStrings
}
