package com.example.myapplication.update

import com.example.myapplication.network.AppLanguage

/**
 * Тексты обновления. Отдельным классом, а не полями `UiStrings`: тот уже у предела числа параметров
 * конструктора (больше 254 роняет release-сборку).
 */
data class UpdateStrings(
    val rowTitle: String,
    val rowChecking: String,
    val rowAvailable: (String) -> String,
    val rowDownloading: (Int) -> String,
    val rowReady: String,
    val rowFailed: String,

    val sheetTitle: String,
    val upToDateTitle: String,
    val upToDateBody: (String) -> String,
    val availableTitle: String,
    val availableBody: (String, String) -> String,
    val downloadingTitle: String,
    val downloadingHint: String,
    val readyTitle: String,
    val readyBody: (String) -> String,
    val installingTitle: String,
    val installingBody: String,
    val permissionTitle: String,
    val permissionBody: String,
    val checkFailedTitle: String,
    val checkFailedBody: String,
    val downloadFailedTitle: String,
    val downloadFailedBody: String,
    val verifyFailedTitle: String,
    val verifyFailedBody: String,
    val installFailedTitle: String,
    val installFailedBody: String,
    val checkingTitle: String,
    val checkingBody: String,

    val updateNow: String,
    val installNow: String,
    val later: String,
    val retry: String,
    val checkNow: String,
    val allowInstalls: String,
    val cancelDownload: String,
    val close: String,
    val openReleasePage: String,

    val unavailableTitle: String,
    val unavailableBody: String,
    val openFdroid: String,

    val autoOnTitle: String,
    val autoOnBody: String,
    val installedLabel: String,
    val latestLabel: String,
    val lastCheckLabel: String,
    val neverChecked: String,
    val justNow: String,
    val minutesAgo: (Int) -> String,
    val hoursAgo: (Int) -> String,
    val daysAgo: (Int) -> String,
    val whatsNew: String,
    val whatsNewEmpty: String,

    val securityTitle: String,
    val signedByAuthor: String,
    val signatureLabel: String,
    val securityBody: String,

    val megabyte: String,
    val perSecond: String,

    val notificationChannel: String,
    val notificationChannelDesc: String,
    val notificationReadyTitle: String,
    val notificationReadyText: (String) -> String,
    val notificationPermissionText: String,
)

private val RU = UpdateStrings(
    rowTitle = "Проверка обновлений",
    rowChecking = "Проверяем…",
    rowAvailable = { "Доступно $it" },
    rowDownloading = { "Загрузка $it%" },
    rowReady = "Готово к установке",
    rowFailed = "Не удалось",

    sheetTitle = "Обновление",
    upToDateTitle = "Установлена последняя версия",
    upToDateBody = { "Vetro $it — самый свежий релиз." },
    availableTitle = "Доступно обновление",
    availableBody = { version, size -> "Версия $version, $size. Vetro скачает и установит её сама." },
    downloadingTitle = "Загружаем обновление",
    downloadingHint = "Можно закрыть окно: загрузка продолжится в фоне",
    readyTitle = "Обновление готово",
    readyBody = { "Версия $it скачана, подпись и контрольная сумма сошлись. Установка займёт несколько секунд." },
    installingTitle = "Устанавливаем",
    installingBody = "Приложение перезапустится само.",
    permissionTitle = "Нужно одно разрешение",
    permissionBody = "Разрешите Vetro устанавливать обновления. Это делается один раз, дальше они будут ставиться сами.",
    checkFailedTitle = "Не удалось проверить",
    checkFailedBody = "Нет связи с GitHub или исчерпан лимит запросов. Попробуем снова позже.",
    downloadFailedTitle = "Загрузка оборвалась",
    downloadFailedBody = "Уже скачанное сохранено, повтор продолжит с того же места.",
    verifyFailedTitle = "Файл не прошёл проверку",
    verifyFailedBody = "Размер, контрольная сумма или подпись не совпали с релизом. Файл удалён и не будет установлен.",
    installFailedTitle = "Установка не удалась",
    installFailedBody = "Система отказалась ставить пакет. Можно повторить или скачать релиз вручную.",
    checkingTitle = "Проверяем",
    checkingBody = "Спрашиваем у GitHub, есть ли новый релиз.",

    updateNow = "Обновить",
    installNow = "Установить",
    later = "Позже",
    retry = "Повторить",
    checkNow = "Проверить сейчас",
    allowInstalls = "Разрешить установку",
    cancelDownload = "Отменить загрузку",
    close = "Закрыть",
    openReleasePage = "Страница релиза",

    unavailableTitle = "Обновления через магазин",
    unavailableBody = "Эта сборка подписана не ключом автора, например она установлена из F-Droid. Встроенное обновление в ней выключено и включить его нельзя: новые версии приходят через магазин, откуда вы её поставили.",
    openFdroid = "Открыть страницу приложения",

    autoOnTitle = "Автообновление включено",
    autoOnBody = "Vetro сама проверяет релизы, скачивает их по Wi‑Fi и сверяет подпись перед установкой.",
    installedLabel = "Установлено",
    latestLabel = "Последний релиз",
    lastCheckLabel = "Проверено",
    neverChecked = "ещё не проверяли",
    justNow = "только что",
    minutesAgo = { "$it мин назад" },
    hoursAgo = { "$it ч назад" },
    daysAgo = { "$it дн. назад" },
    whatsNew = "Что нового",
    whatsNewEmpty = "У этого релиза нет описания",

    securityTitle = "Безопасность",
    signedByAuthor = "Подписано ключом автора",
    signatureLabel = "Отпечаток SHA-256",
    securityBody = "Перед установкой проверяются размер файла, контрольная сумма SHA-256 и подпись: пакет, подписанный другим ключом, не будет установлен.",

    megabyte = "МБ",
    perSecond = "МБ/с",

    notificationChannel = "Обновления Vetro",
    notificationChannelDesc = "Когда обновление скачано и ждёт подтверждения",
    notificationReadyTitle = "Обновление Vetro готово",
    notificationReadyText = { "Нажмите, чтобы установить $it" },
    notificationPermissionText = "Разрешите установку, чтобы обновления ставились сами",
)

private val EN = UpdateStrings(
    rowTitle = "Check for updates",
    rowChecking = "Checking…",
    rowAvailable = { "$it available" },
    rowDownloading = { "Downloading $it%" },
    rowReady = "Ready to install",
    rowFailed = "Failed",

    sheetTitle = "Update",
    upToDateTitle = "You're up to date",
    upToDateBody = { "Vetro $it is the latest release." },
    availableTitle = "Update available",
    availableBody = { version, size -> "Version $version, $size. Vetro will download and install it on its own." },
    downloadingTitle = "Downloading the update",
    downloadingHint = "You can close this: the download keeps going in the background",
    readyTitle = "Update ready",
    readyBody = { "Version $it is downloaded, and its signature and checksum match. Installing takes a few seconds." },
    installingTitle = "Installing",
    installingBody = "The app restarts by itself.",
    permissionTitle = "One permission needed",
    permissionBody = "Allow Vetro to install updates. You do this once; after that they install on their own.",
    checkFailedTitle = "Couldn't check",
    checkFailedBody = "GitHub is unreachable or the request limit is used up. We'll try again later.",
    downloadFailedTitle = "Download interrupted",
    downloadFailedBody = "What is already downloaded is kept; retrying continues from the same place.",
    verifyFailedTitle = "The file failed verification",
    verifyFailedBody = "Its size, checksum or signature didn't match the release. The file was deleted and will not be installed.",
    installFailedTitle = "Installation failed",
    installFailedBody = "The system refused to install the package. You can retry or download the release by hand.",
    checkingTitle = "Checking",
    checkingBody = "Asking GitHub whether there is a new release.",

    updateNow = "Update",
    installNow = "Install",
    later = "Later",
    retry = "Retry",
    checkNow = "Check now",
    allowInstalls = "Allow installs",
    cancelDownload = "Cancel download",
    close = "Close",
    openReleasePage = "Release page",

    unavailableTitle = "Updates come from your store",
    unavailableBody = "This build isn't signed with the author's key, for example it was installed from F-Droid. Built-in updating is off here and can't be turned on: new versions arrive through the store you installed it from.",
    openFdroid = "Open the app page",

    autoOnTitle = "Auto-update is on",
    autoOnBody = "Vetro checks releases on its own, downloads them over Wi‑Fi and verifies the signature before installing.",
    installedLabel = "Installed",
    latestLabel = "Latest release",
    lastCheckLabel = "Checked",
    neverChecked = "not yet",
    justNow = "just now",
    minutesAgo = { "$it min ago" },
    hoursAgo = { "$it h ago" },
    daysAgo = { "$it d ago" },
    whatsNew = "What's new",
    whatsNewEmpty = "This release has no notes",

    securityTitle = "Security",
    signedByAuthor = "Signed with the author's key",
    signatureLabel = "SHA-256 fingerprint",
    securityBody = "Before installing, Vetro checks the file size, the SHA-256 checksum and the signature: a package signed with another key will not be installed.",

    megabyte = "MB",
    perSecond = "MB/s",

    notificationChannel = "Vetro updates",
    notificationChannelDesc = "When an update is downloaded and waits for confirmation",
    notificationReadyTitle = "Vetro update ready",
    notificationReadyText = { "Tap to install $it" },
    notificationPermissionText = "Allow installs so updates can install on their own",
)

fun updateStrings(language: AppLanguage): UpdateStrings = if (language == AppLanguage.RU) RU else EN
