package com.example.myapplication.domain.stats

import com.example.myapplication.network.AppLanguage

/**
 * Тексты блока «Инсайты» статистики. Отдельно от UiStrings: в нём уже ~250 полей, а предел JVM на
 * параметры конструктора — 255 (см. память «UiStrings 255-param limit»).
 */
data class StatsInsightsStrings(
    val sectionTitle: String,
    val filterAll: String,
    val filterWatch: String,
    val filterRead: String,
    val filterListen: String,
    val activityTitle: String,
    val activityEmpty: String,
    val activeDays: (Int) -> String,
    val bestDay: (date: String, units: Int) -> String,
    val peakWeekday: (String) -> String,
    val legendLess: String,
    val legendMore: String,
    val monthlyTitle: String,
    val monthlyBest: (month: String, units: Int) -> String,
    val monthlyEmpty: String,
    val returnsTitle: String,
    val rewatch: String,
    val reread: String,
    val relisten: String,
    val returnsCaption: String,
    val unitEpisodes: (Int) -> String,
    val unitChapters: (Int) -> String,
    val unitBooks: (Int) -> String,
    val genreQualityTitle: String,
    val genreQualityEmpty: String,
    val completedLabel: String,
    val droppedLabel: String,
    val returnedLabel: String,
    val genreQualityNote: String,
    val profileTitle: String,
    val profileRecentLabel: (days: Int) -> String,
    val profileOverallLabel: String,
    val profileNotEnough: String,
    val profileSummary: (recent: Int, total: Int) -> String,
    val profileRating: (recent: String, overall: String) -> String,
    val donutCenterCaption: String,
    val donutFootnote: String,
    val donutLegendDetail: (count: Int, total: Int, percent: Int) -> String,
    val sourcesTitle: String,
    val sourcesEmpty: String,
    val sourcesNote: String,
    val sourcesDetail: (resolvePercent: Int?, startupSeconds: String?, heightPx: Int?) -> String,
)

fun statsInsightsStrings(language: AppLanguage): StatsInsightsStrings =
    if (language == AppLanguage.RU) RU_STRINGS else EN_STRINGS

private val RU_STRINGS = StatsInsightsStrings(
    sectionTitle = "ИНСАЙТЫ",
    filterAll = "Всё",
    filterWatch = "Смотрел",
    filterRead = "Читал",
    filterListen = "Слушал",
    activityTitle = "Активность по дням",
    activityEmpty = "Пока нет следов просмотра, чтения и прослушивания — они появятся, когда вы начнёте.",
    activeDays = { n -> "Активных дней: $n" },
    bestDay = { date, units -> "лучший день — $date ($units)" },
    peakWeekday = { day -> "чаще всего: $day" },
    legendLess = "меньше",
    legendMore = "больше",
    monthlyTitle = "По месяцам",
    monthlyBest = { month, units -> "пик — $month, $units" },
    monthlyEmpty = "За последний год активности нет.",
    returnsTitle = "Возвраты",
    rewatch = "Пересмотр",
    reread = "Перечитано",
    relisten = "Переслушано",
    returnsCaption = "Тайтлы, к которым вы вернулись после финала. Книга считается переслушанной, когда вы прослушали её больше 1,6 раза.",
    unitEpisodes = { n -> "$n эп." },
    unitChapters = { n -> "$n гл." },
    unitBooks = { n -> if (n == 1) "книга" else "книг" },
    genreQualityTitle = "Жанры: досмотр и бросание",
    genreQualityEmpty = "Недостаточно начатых тайтлов в жанрах.",
    completedLabel = "досмотрено",
    droppedLabel = "брошено",
    returnedLabel = "возвраты",
    genreQualityNote = "Брошенным считается начатое без движения 90 дней и больше. Оценённое — завершённое.",
    profileTitle = "Профиль сейчас и в целом",
    profileRecentLabel = { days -> "последние $days дн." },
    profileOverallLabel = "вся коллекция",
    profileNotEnough = "За последние 90 дней добавлено слишком мало — сравнивать пока не с чем.",
    profileSummary = { recent, total -> "Добавлено недавно: $recent из $total" },
    profileRating = { recent, overall -> "Средняя оценка: $recent сейчас · $overall в целом" },
    donutCenterCaption = "тайтлов",
    donutFootnote = "У тайтла несколько жанров, поэтому доли в сумме больше 100%.",
    donutLegendDetail = { count, total, percent -> "$count из $total · $percent%" },
    sourcesTitle = "Источники на этом устройстве",
    sourcesEmpty = "Пока нечего сравнивать: оценки появятся после нескольких просмотров.",
    sourcesNote = "Оценка 0–100 из доли удачных ответов, скорости, старта, буферизации, реального разрешения и сохранения озвучки. При прочих равных первыми идут источники с высокой оценкой.",
    sourcesDetail = { resolve, startup, height ->
        listOfNotNull(
            resolve?.let { "ответ $it%" },
            startup?.let { "старт $it с" },
            height?.let { "${it}p" },
        ).joinToString(" · ")
    },
)

private val EN_STRINGS = StatsInsightsStrings(
    sectionTitle = "INSIGHTS",
    filterAll = "All",
    filterWatch = "Watched",
    filterRead = "Read",
    filterListen = "Listened",
    activityTitle = "Activity by day",
    activityEmpty = "No watching, reading or listening yet — it shows up as soon as you start.",
    activeDays = { n -> "Active days: $n" },
    bestDay = { date, units -> "best day — $date ($units)" },
    peakWeekday = { day -> "most often: $day" },
    legendLess = "less",
    legendMore = "more",
    monthlyTitle = "By month",
    monthlyBest = { month, units -> "peak — $month, $units" },
    monthlyEmpty = "No activity in the last year.",
    returnsTitle = "Returns",
    rewatch = "Rewatched",
    reread = "Reread",
    relisten = "Relistened",
    returnsCaption = "Titles you came back to after the ending. A book counts as relistened once you have played it through 1.6 times.",
    unitEpisodes = { n -> "$n ep." },
    unitChapters = { n -> "$n ch." },
    unitBooks = { n -> if (n == 1) "book" else "books" },
    genreQualityTitle = "Genres: finished and dropped",
    genreQualityEmpty = "Not enough started titles in your genres.",
    completedLabel = "finished",
    droppedLabel = "dropped",
    returnedLabel = "returns",
    genreQualityNote = "Dropped means started and untouched for 90+ days. Rated counts as finished.",
    profileTitle = "Profile now vs overall",
    profileRecentLabel = { days -> "last $days days" },
    profileOverallLabel = "whole collection",
    profileNotEnough = "Too little added in the last 90 days to compare yet.",
    profileSummary = { recent, total -> "Added recently: $recent of $total" },
    profileRating = { recent, overall -> "Average rating: $recent now · $overall overall" },
    donutCenterCaption = "titles",
    donutFootnote = "A title has several genres, so the shares add up to more than 100%.",
    donutLegendDetail = { count, total, percent -> "$count of $total · $percent%" },
    sourcesTitle = "Sources on this device",
    sourcesEmpty = "Nothing to compare yet: scores appear after a few viewings.",
    sourcesNote = "A 0-100 score from answer rate, speed, startup, buffering, real resolution and dub continuity. When all else is equal, higher-scored sources go first.",
    sourcesDetail = { resolve, startup, height ->
        listOfNotNull(
            resolve?.let { "answers $it%" },
            startup?.let { "start ${it}s" },
            height?.let { "${it}p" },
        ).joinToString(" · ")
    },
)
